class Solution:
    def reformatDate(self, date: str) -> str:
        res=''
        print(len(date))
        if(len(date)==12):
            res+='0'
            res+=date[0]
            res+='-'
            if(date[4]+date[5]+date[6]=="Jan"):
                res+='0'
                res+='1'
            elif(date[4]+date[5]+date[6]=="Feb"):
                res+='0'
                res+='2'
            elif(date[4]+date[5]+date[6]=="Mar"):
                res+='0'
                res+='3'
            elif(date[4]+date[5]+date[6]=="Apr"):
                res+='0'
                res+='4'
            elif(date[4]+date[5]+date[6]=="May"):
                res+='0'
                res+='5'
            elif(date[4]+date[5]+date[6]=="Jun"):
                res+='0'
                res+='6'
            elif(date[4]+date[5]+date[6]=="Jul"):
                res+='0'
                res+='7'
            elif(date[4]+date[5]+date[6]=="Aug"):
                res+='0'
                res+='8'
            elif(date[4]+date[5]+date[6]=="Sep"):
                res+='0'
                res+='9'
            elif(date[4]+date[5]+date[6]=="Oct"):
                res+='1'
                res+='0'
            elif(date[4]+date[5]+date[6]=="Nov"):
                res+='1'
                res+='1'
            else:
                res+='1'
                res+='2'
            res+="-"
            res+=date[8]
            res+=date[9]
            res+=date[10]
            res+=date[11]
        if(len(date)==13):
            res+=date[0]
            res+=date[1]
            res+='-'
            if(date[5]+date[6]+date[7]=="Jan"):
                res+='0'
                res+='1'
            elif(date[5]+date[6]+date[7]=="Feb"):
                res+='0'
                res+='2'
            elif(date[5]+date[6]+date[7]=="Mar"):
                res+='0'
                res+='3'
            elif(date[5]+date[6]+date[7]=="Apr"):
                res+='0'
                res+='4'
            elif(date[5]+date[6]+date[7]=="May"):
                res+='0'
                res+='5'
            elif(date[5]+date[6]+date[7]=="Jun"):
                res+='0'
                res+='6'
            elif(date[5]+date[6]+date[7]=="Jul"):
                res+='0'
                res+='7'
            elif(date[5]+date[6]+date[7]=="Aug"):
                res+='0'
                res+='8'
            elif(date[5]+date[6]+date[7]=="Sep"):
                res+='0'
                res+='9'
            elif(date[5]+date[6]+date[7]=="Oct"):
                res+='1'
                res+='0'
            elif(date[5]+date[6]+date[7]=="Nov"):
                res+='1'
                res+='1'
            elif(date[5]+date[6]+date[7]=="Dec"):
                res+='1'
                res+='2'
            res+="-"
            res+=date[9]
            res+=date[10]
            res+=date[11]
            res+=date[12]
        res=res[::-1]
        p=''
        ans=''
        for i in range(len(res)):
            if(res[i]!='-'):
                p+=res[i]
            else:
                ans+=p[::-1]
                ans+='-'
                p=''
        ans+=p[::-1]
        return ans

        